name: Rebuild WordPress container daily

on:
  schedule:
    - cron: '0 4 * * *' # Dagelijks om 04:00
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build image
      run: docker build -t jos/wordpress-redis:latest .

    - name: Done
      run: echo "Container build complete."