name: Build & Push WordPress container

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/wordpress-redis:latest .

    - name: Push image
      run: docker push ghcr.io/${{ github.repository_owner }}/wordpress-redis:latest